version: '3.4'

services:

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

#  webapplication:
#    image: ${DOCKER_REGISTRY-}webapplication
#    build:
#      context: .
#      dockerfile: src/Presentation/WebApplication/Dockerfile

  instruments.query.service:
    image: ${DOCKER_REGISTRY-}instrumentsqueryservice
    build:
      context: .
      dockerfile: src/Instruments/Instruments.Query.Service/Dockerfile

  instruments.service:
    image: ${DOCKER_REGISTRY-}instrumentsservice
    build:
      context: .
      dockerfile: src/Instruments/Instruments.Service/Dockerfile

  marketcurves.query.service:
    image: ${DOCKER_REGISTRY-}marketcurvesqueryservice
    build:
      context: .
      dockerfile: src/MarketCurves/MarketCurves.Query.Service/Dockerfile

  marketcurves.service:
    image: ${DOCKER_REGISTRY-}marketcurvesservice
    build:
      context: .
      dockerfile: src/MarketCurves/MarketCurves.Service/Dockerfile


  curverecipes.service:
    image: ${DOCKER_REGISTRY-}curverecipesservice
    build:
      context: .
      dockerfile: src/CurveRecipes/CurveRecipes.Service/Dockerfile


  curverecipes.query.service:
    image: ${DOCKER_REGISTRY-}curverecipesqueryservice
    build:
      context: .
      dockerfile: src/CurveRecipes/CurveRecipes.Query.Service/Dockerfile

  # apigateway:
    # image: ${DOCKER_REGISTRY-}apigateway
    # build:
      # context: .
      # dockerfile: src/Gateway/ApiGateway/Dockerfile
  # pricepublisher.service:
    # image: ${DOCKER_REGISTRY-}pricepublisherservice
    # build:
      # context: .
      # dockerfile: src/PricePublisher/PricePublisher.Service/Dockerfile

#  calculationengine.service:
#    image: ${DOCKER_REGISTRY-}calculationengineservice
#    build:
#      context: .
#      dockerfile: src/CalculationEngine/CalculationEngine.Service/Dockerfile

#  frontend:
#    build:
#      context: src/Presentation/MicroFrontends/curve-tool
#      dockerfile: Dockerfile
#    ports:
#      - 8081:8080
#    stdin_open: true
#    tty: true  
#    volumes:
#      - "./src/Presentation/MicroFrontends/curve-tool:/app"
#      - '/app/node_modules'
#    environment:
#      - CHOKIDAR_USEPOLLING=true